SELECT * FROM EMPLOYEES e ;

           -- 1 --
SELECT * FROM EMPLOYEES e 
WHERE E.EMPLOYEE_ID BETWEEN 100 AND 105;

            -- 2 --
SELECT * FROM EMPLOYEES e 
WHERE E.EMPLOYEE_ID IN (151,152,153,154);

            -- 3 --
SELECT * FROM EMPLOYEES e 
WHERE INITCAP(E.FIRST_NAME) LIKE 'P%' ;


         -- 3- Another Solution --
SELECT * FROM EMPLOYEES e 
WHERE (E.FIRST_NAME BETWEEN  'P' and 'Q' ) OR ( E.FIRST_NAME BETWEEN 'p' AND 'q' );


           -- 4 --
SELECT * FROM EMPLOYEES e 
WHERE INITCAP(E.FIRST_NAME) LIKE '%A' ;


           -- 5 --
SELECT * FROM EMPLOYEES e 
WHERE INITCAP(E.FIRST_NAME) LIKE 'A%' ;


            -- 6 --
SELECT * FROM EMPLOYEES e 
WHERE e.FIRST_NAME LIKE '__a%' ;

			-- 7 --
SELECT * FROM EMPLOYEES e 
WHERE e.MANAGER_ID IS NULL ;


			-- 8 --
SELECT * FROM EMPLOYEES e 
WHERE e.MANAGER_ID IS NOT NULL ;


			-- 9 --
INSERT INTO EMPLOYEES ( employee_id ,FIRST_NAME , LAST_NAME , EMAIL , PHONE_NUMBER , HIRE_DATE , JOB_ID , SALARY , COMMISSION_PCT , MANAGER_ID , DEPARTMENT_ID) 
VALUES ( 207 , 'MOHAMED', 'SALAH' , 'MS@outlook.com' ,'0122244' , sysdate-365*7 ,'IT_PROG' ,4500 , NULL ,NULL , 30);



			-- 10 --
SELECT * FROM EMPLOYEES e 
WHERE E.JOB_ID IN ('AD_VP' , 'IT_PROG');


			-- 11 --
SELECT * FROM EMPLOYEES E
ORDER BY E.LAST_NAME ASC;


			  -- 12 --
SELECT * FROM EMPLOYEES E
ORDER BY E.HIRE_DATE DESC;


              -- 13 --
SELECT * FROM EMPLOYEES e 
ORDER BY E.DEPARTMENT_ID ASC , E.SALARY DESC;


              -- 14 --
SELECT e.EMPLOYEE_ID , E.FIRST_NAME , LOWER(E.LAST_NAME)  FROM EMPLOYEES e 


              -- 15 --
SELECT e.EMPLOYEE_ID , UPPER(E.FIRST_NAME )  FROM EMPLOYEES e 


               -- 16 --
SELECT INITCAP(e.FIRST_NAME)  || ' ' || E.LAST_NAME  "FULL NAME"  FROM EMPLOYEES e ;


-- 17 --
SELECT *  FROM EMPLOYEES e 
WHERE UPPER(E.LAST_NAME)  = 'SMITH';