SELECT REPLACE('DATABASE', 'A' , '@') FROM DUAL;

SELECT REPLACE ('OLD THINGS NEVER COME OLD' , 'OLD' , 'NEW') FROM DUAL;

CREATE TABLE PRODUCTS(
P_NAME VARCHAR2(40)
)

INSERT INTO PRODUCTS VALUES ('MILK');
INSERT INTO PRODUCTS VALUES ('SWEETS');
INSERT INTO PRODUCTS VALUES ('BREAD');

SELECT * FROM PRODUCTS ;

SELECT LPAD( P_NAME ,15 ,'*' ) FROM PRODUCTS;

SELECT RPAD ( P_NAME ,15 ,'#' ) FROM PRODUCTS;